#!/usr/bin/env python3

import rospy
from nav_msgs.msg import Path
from geometry_msgs.msg import PoseStamped

class PathPublisher:
    def __init__(self):
        rospy.init_node('path_publisher', anonymous=True)
        
        self.path_pub = rospy.Publisher('/gps_path', Path, queue_size=10)
        
        self.path = self.generate_path()
        self.timer = rospy.Timer(rospy.Duration(5), self.publish_path)

    def generate_path(self):
        path = Path()
        path.header.frame_id = "map"
        
        for i in range(0, 21):
            pose = PoseStamped()
            pose.header.frame_id = "map"
            pose.header.stamp = rospy.Time.now()

            pose.pose.position.x = i * 3     # X coordinate
            pose.pose.position.y = 0.0       # Y coordinate
            pose.pose.position.z = 0.0       # Z coordinate

            pose.pose.orientation.w = 1.0
            pose.pose.orientation.x = 0.0
            pose.pose.orientation.y = 0.0
            pose.pose.orientation.z = 0.0

            path.poses.append(pose)

        return path

    def publish_path(self, event):
        self.path.header.stamp = rospy.Time.now()
        self.path_pub.publish(self.path)

if __name__ == '__main__':
    try:
        path_publisher = PathPublisher()
        rospy.spin()
    except rospy.ROSInterruptException:
        pass
